
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AF', 'AFG', 004, 'Afeganistão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ZA', 'ZAF', '710', 'África do Sul',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AX', 'ALA', '248', 'Åland, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AL', 'ALB', '008', 'Albânia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('DE', 'DEU', '276', 'Alemanha',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AD', 'AND', '020', 'Andorra',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AO', 'AGO', '024', 'Angola',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AI', 'AIA', '660', 'Anguilla',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AQ', 'ATA', '010', 'Antárctida',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AG', 'ATG', '028', 'Antigua e Barbuda',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AN', 'ANT', '530', 'Antilhas Holandesas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SA', 'SAU', '682', 'Arábia Saudita',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('DZ', 'DZA', '012', 'Argélia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AR', 'ARG', '032', 'Argentina',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AM', 'ARM', '051', 'Arménia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AW', 'ABW', '533', 'Aruba',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AU', 'AUS', '036', 'Austrália',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AT', 'AUT', '040', 'Áustria',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AZ', 'AZE', '031', 'Azerbeijão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BS', 'BHS', '044', 'Bahamas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BH', 'BHR', '048', 'Bahrain',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BD', 'BGD', '050', 'Bangladesh',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BB', 'BRB', '052', 'Barbados',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BE', 'BEL', '056', 'Bélgica',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BZ', 'BLZ', '084', 'Belize',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BJ', 'BEN', '204', 'Benin',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BM', 'BMU', '060', 'Bermuda',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BY', 'BLR', '112', 'Bielo-Rússia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BO', 'BOL', '068', 'Bolívia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BA', 'BIH', '070', 'Bósnia-Herzegovina',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BW', 'BWA', '072', 'Botswana',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BV', 'BVT', '074', 'Bouvet, Ilha',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BR', 'BRA', '076', 'Brasil',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BN', 'BRN', '096', 'Brunei',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BG', 'BGR', '100', 'Bulgária',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BF', 'BFA', '854', 'Burkina Faso',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BI', 'BDI', '108', 'Burundi',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('BT', 'BTN', '064', 'Butão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CV', 'CPV', '132', 'Cabo Verde',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KH', 'KHM', '116', 'Cambodja',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CM', 'CMR', '120', 'Camarões',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CA', 'CAN', '124', 'Canadá',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KY', 'CYM', '136', 'Cayman, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KZ', 'KAZ', '398', 'Cazaquistão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CF', 'CAF', '140', 'Centro-africana, República',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TD', 'TCD', '148', 'Chade',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CZ', 'CZE', '203', 'Checa, República',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CL', 'CHL', '152', 'Chile',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CN', 'CHN', '156', 'China',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CY', 'CYP', '196', 'Chipre',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CX', 'CXR', '162', 'Christmas, Ilha',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CC', 'CCK', '166', 'Cocos, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CO', 'COL', '170', 'Colômbia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KM', 'COM', '174', 'Comores',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CG', 'COG', '178', 'Congo, República do',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CD', 'COD', '180', 'Congo, República Democrática do (antigo Zaire)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CK', 'COK', '184', 'Cook, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KR', 'KOR', '410', 'Coreia do Sul',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KP', 'PRK', '408', 'Coreia, República Democrática da (Coreia do Norte)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CI', 'CIV', '384', 'Costa do Marfim',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CR', 'CRI', '188', 'Costa Rica',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('HR', 'HRV', '191', 'Croácia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CU', 'CUB', '192', 'Cuba',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('DK', 'DNK', '208', 'Dinamarca',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('DJ', 'DJI', '262', 'Djibouti',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('DM', 'DMA', '212', 'Dominica',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('DO', 'DOM', '214', 'Dominicana, República',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('EG', 'EGY', '818', 'Egipto',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SV', 'SLV', '222', 'El Salvador',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AE', 'ARE', '784', 'Emiratos Árabes Unidos',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('EC', 'ECU', '218', 'Equador',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ER', 'ERI', '232', 'Eritreia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SK', 'SVK', '703', 'Eslováquia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SI', 'SVN', '705', 'Eslovénia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ES', 'ESP', '724', 'Espanha',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('US', 'USA', '840', 'Estados Unidos da América',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('EE', 'EST', '233', 'Estónia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ET', 'ETH', '231', 'Etiópia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('FO', 'FRO', '234', 'Faroe, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('FJ', 'FJI', '242', 'Fiji',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PH', 'PHL', '608', 'Filipinas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('FI', 'FIN', '246', 'Finlândia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('FR', 'FRA', '250', 'França',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GA', 'GAB', '266', 'Gabão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GM', 'GMB', '270', 'Gâmbia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GH', 'GHA', '288', 'Gana',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GE', 'GEO', '268', 'Geórgia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GS', 'SGS', '239', 'Geórgia do Sul e Sandwich do Sul, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GI', 'GIB', '292', 'Gibraltar',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GR', 'GRC', '300', 'Grécia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GD', 'GRD', '308', 'Grenada',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GL', 'GRL', '304', 'Gronelândia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GP', 'GLP', '312', 'Guadeloupe',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GU', 'GUM', '316', 'Guam',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GT', 'GTM', '320', 'Guatemala',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GG', 'GGY', '831', 'Guernsey',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GY', 'GUY', '328', 'Guiana',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GF', 'GUF', '254', 'Guiana Francesa',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GW', 'GNB', '624', 'Guiné-Bissau',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GN', 'GIN', '324', 'Guiné-Conacri',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GQ', 'GNQ', '226', 'Guiné Equatorial',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('HT', 'HTI', '332', 'Haiti',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('HM', 'HMD', '334', 'Heard e Ilhas McDonald, Ilha',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('HN', 'HND', '340', 'Honduras',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('HK', 'HKG', '344', 'Hong Kong',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('HU', 'HUN', '348', 'Hungria',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('YE', 'YEM', '887', 'Iémen',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IN', 'IND', '356', 'Índia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ID', 'IDN', '360', 'Indonésia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IQ', 'IRQ', '368', 'Iraque',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IR', 'IRN', '364', 'Irão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IE', 'IRL', '372', 'Irlanda',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IS', 'ISL', '352', 'Islândia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IL', 'ISR', '376', 'Israel',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IT', 'ITA', '380', 'Itália',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('JM', 'JAM', '388', 'Jamaica',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('JP', 'JPN', '392', 'Japão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('JE', 'JEY', '832', 'Jersey',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('JO', 'JOR', '400', 'Jordânia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KI', 'KIR', '296', 'Kiribati',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KW', 'KWT', '414', 'Kuwait',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LA', 'LAO', '418', 'Laos',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LS', 'LSO', '426', 'Lesoto',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LV', 'LVA', '428', 'Letónia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LB', 'LBN', '422', 'Líbano',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LR', 'LBR', '430', 'Libéria',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LY', 'LBY', '434', 'Líbia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LI', 'LIE', '438', 'Liechtenstein',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LT', 'LTU', '440', 'Lituânia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LU', 'LUX', '442', 'Luxemburgo',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MO', 'MAC', '446', 'Macau',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MK', 'MKD', '807', 'Macedónia, República da',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MG', 'MDG', '450', 'Madagáscar',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MY', 'MYS', '458', 'Malásia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MW', 'MWI', '454', 'Malawi',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MV', 'MDV', '462', 'Maldivas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ML', 'MLI', '466', 'Mali',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MT', 'MLT', '470', 'Malta',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('FK', 'FLK', '238', 'Malvinas, Ilhas (Falkland)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IM', 'IMN', '833', 'Man, Ilha de',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MP', 'MNP', '580', 'Marianas Setentrionais',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MA', 'MAR', '504', 'Marrocos',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MH', 'MHL', '584', 'Marshall, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MQ', 'MTQ', '474', 'Martinica',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MU', 'MUS', '480', 'Maurícia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MR', 'MRT', '478', 'Mauritânia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('YT', 'MYT', '175', 'Mayotte',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('UM', 'UMI', '581', 'Menores Distantes dos Estados Unidos, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MX', 'MEX', '484', 'México',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MM', 'MMR', '104', 'Myanmar (antiga Birmânia)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('FM', 'FSM', '583', 'Micronésia, Estados Federados da',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MZ', 'MOZ', '508', 'Moçambique',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MD', 'MDA', '498', 'Moldávia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MC', 'MCO', '492', 'Mónaco',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MN', 'MNG', '496', 'Mongólia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ME', 'MNE', '499', 'Montenegro',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('MS', 'MSR', '500', 'Montserrat',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NA', 'NAM', '516', 'Namíbia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NR', 'NRU', '520', 'Nauru',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NP', 'NPL', '524', 'Nepal',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NI', 'NIC', '558', 'Nicarágua',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NE', 'NER', '562', 'Níger',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NG', 'NGA', '566', 'Nigéria',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NU', 'NIU', '570', 'Niue',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NF', 'NFK', '574', 'Norfolk, Ilha',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NO', 'NOR', '578', 'Noruega',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NC', 'NCL', '540', 'Nova Caledónia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NZ', 'NZL', '554', 'Nova Zelândia (Aotearoa)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('OM', 'OMN', '512', 'Oman',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('NL', 'NLD', '528', 'Países Baixos (Holanda)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PW', 'PLW', '585', 'Palau',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PS', 'PSE', '275', 'Palestina',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PA', 'PAN', '591', 'Panamá',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PG', 'PNG', '598', 'Papua-Nova Guiné',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PK', 'PAK', '586', 'Paquistão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PY', 'PRY', '600', 'Paraguai',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PE', 'PER', '604', 'Peru',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PN', 'PCN', '612', 'Pitcairn',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PF', 'PYF', '258', 'Polinésia Francesa',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PL', 'POL', '616', 'Polónia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PR', 'PRI', '630', 'Porto Rico',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PT', 'PRT', '620', 'Portugal',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('QA', 'QAT', '634', 'Qatar',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KE', 'KEN', '404', 'Quénia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KG', 'KGZ', '417', 'Quirguistão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('GB', 'GBR', '826', 'Reino Unido da Grã-Bretanha e Irlanda do Norte',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('RE', 'REU', '638', 'Reunião',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('RO', 'ROU', '642', 'Roménia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('RW', 'RWA', '646', 'Ruanda',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('RU', 'RUS', '643', 'Rússia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('EH', 'ESH', '732', 'Saara Ocidental',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('AS', 'ASM', '016', 'Samoa Americana',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('WS', 'WSM', '882', 'Samoa (Samoa Ocidental)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('PM', 'SPM', '666', 'Saint Pierre et Miquelon',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SB', 'SLB', '090', 'Salomão, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('KN', 'KNA', '659', 'São Cristóvão e Névis (Saint Kitts e Nevis)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SM', 'SMR', '674', 'San Marino',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ST', 'STP', '678', 'São Tomé e Príncipe',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('VC', 'VCT', '670', 'São Vicente e Granadinas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SH', 'SHN', '654', 'Santa Helena',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LC', 'LCA', '662', 'Santa Lúcia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SN', 'SEN', '686', 'Senegal',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SL', 'SLE', '694', 'Serra Leoa',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('RS', 'SRB', '688', 'Sérvia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SC', 'SYC', '690', 'Seychelles',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SG', 'SGP', '702', 'Singapura',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SY', 'SYR', '760', 'Síria',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SO', 'SOM', '706', 'Somália',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('LK', 'LKA', '144', 'Sri Lanka',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SZ', 'SWZ', '748', 'Suazilândia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SD', 'SDN', '736', 'Sudão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SE', 'SWE', '752', 'Suécia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('CH', 'CHE', '756', 'Suíça',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SR', 'SUR', '740', 'Suriname',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('SJ', 'SJM', '744', 'Svalbard e Jan Mayen',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TH', 'THA', '764', 'Tailândia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TW', 'TWN', '158', 'Taiwan',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TJ', 'TJK', '762', 'Tajiquistão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TZ', 'TZA', '834', 'Tanzânia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TF', 'ATF', '260', 'Terras Austrais e Antárticas Francesas (TAAF)',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('IO', 'IOT', '086', 'Território Britânico do Oceano Índico',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TL', 'TLS', '626', 'Timor-Leste',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TG', 'TGO', '768', 'Togo',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TK', 'TKL', '772', 'Toquelau',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TO', 'TON', '776', 'Tonga',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TT', 'TTO', '780', 'Trindade e Tobago',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TN', 'TUN', '788', 'Tunísia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TC', 'TCA', '796', 'Turks e Caicos',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TM', 'TKM', '795', 'Turquemenistão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TR', 'TUR', '792', 'Turquia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('TV', 'TUV', '798', 'Tuvalu',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('UA', 'UKR', '804', 'Ucrânia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('UG', 'UGA', '800', 'Uganda',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('UY', 'URY', '858', 'Uruguai',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('UZ', 'UZB', '860', 'Usbequistão',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('VU', 'VUT', '548', 'Vanuatu',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('VA', 'VAT', '336', 'Vaticano',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('VE', 'VEN', '862', 'Venezuela',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('VN', 'VNM', '704', 'Vietname',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('VI', 'VIR', '850', 'Virgens Americanas, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('VG', 'VGB', '092', 'Virgens Britânicas, Ilhas',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('WF', 'WLF', '876', 'Wallis e Futuna',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ZM', 'ZMB', '894', 'Zâmbia',getdate(), getdate(), 1);
INSERT INTO dbo.Paises (Iso, Iso3, Code, Nome,  AddedDate, ModifiedDate, Ativo)  VALUES ('ZW', 'ZWE', '716', 'Zimbabwe',getdate(), getdate(), 1);