version: '2.3'
services:
  services:
    image: dockeragrobook
    build:
      context: .
      dockerfile: Dockerfile

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'alpacatracker.com -> http://app:5000'
      STAGE: 'production'
    
#    networks:
#      - agrobook-network  

#networks: 
#    agrobook-network:
#        driver: bridge