version: '2.3'

services:
  app:  
   image: dockeragrobook
   build:
     context: .
     dockerfile: Dockerfile

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'agrobook.xyz -> http://app:1500'
      STAGE: 'production'
    
#    networks:
#      - agrobook-network  

#networks: 
#    agrobook-network:
#        driver: bridge