//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agrobook.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rsc_Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rsc_Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agrobook.Application.Rsc_Message", typeof(Rsc_Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASS.
        /// </summary>
        internal static string ASS {
            get {
                return ResourceManager.GetString("ASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCC.
        /// </summary>
        internal static string DCC {
            get {
                return ResourceManager.GetString("DCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPCC.
        /// </summary>
        internal static string DPCC {
            get {
                return ResourceManager.GetString("DPCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCC.
        /// </summary>
        internal static string FCC {
            get {
                return ResourceManager.GetString("FCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDC.
        /// </summary>
        internal static string FDC {
            get {
                return ResourceManager.GetString("FDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUC.
        /// </summary>
        internal static string FUC {
            get {
                return ResourceManager.GetString("FUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICC.
        /// </summary>
        internal static string ICC {
            get {
                return ResourceManager.GetString("ICC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IUC.
        /// </summary>
        internal static string IUC {
            get {
                return ResourceManager.GetString("IUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCC.
        /// </summary>
        internal static string OCC {
            get {
                return ResourceManager.GetString("OCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUC.
        /// </summary>
        internal static string OUC {
            get {
                return ResourceManager.GetString("OUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificar incorreto ou registro não encontrado!.
        /// </summary>
        internal static string RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMCC.
        /// </summary>
        internal static string UMCC {
            get {
                return ResourceManager.GetString("UMCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMDC.
        /// </summary>
        internal static string UMDC {
            get {
                return ResourceManager.GetString("UMDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMUC.
        /// </summary>
        internal static string UMUC {
            get {
                return ResourceManager.GetString("UMUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCC.
        /// </summary>
        internal static string VCC {
            get {
                return ResourceManager.GetString("VCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDC.
        /// </summary>
        internal static string VDC {
            get {
                return ResourceManager.GetString("VDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VUC.
        /// </summary>
        internal static string VUC {
            get {
                return ResourceManager.GetString("VUC", resourceCulture);
            }
        }
    }
}
